esphome:
  name: esp32-cam
  friendly_name: ESP32-CAM

esp32:
  board: esp32dev
  framework:
    type: arduino

psram:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: "ESP32-CAM Fallback"
    password: !secret ap_password

captive_portal:

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins:
    - GPIO5
    - GPIO18
    - GPIO19
    - GPIO21
    - GPIO36
    - GPIO39
    - GPIO34
    - GPIO35
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  max_framerate: 60 fps
  idle_framerate: 0.2 fps
  resolution: 800x600
  jpeg_quality: 12
  brightness: 0
  contrast: 0
  saturation: 0

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_flash

light:
  - platform: binary
    output: gpio_flash
    name: "Flashlight"
    id: flashlight
    icon: mdi:flashlight
    restore_mode: ALWAYS_OFF
